### PR TITLE
Add Hydrodata

### PR DESCRIPTION
**Pull request by cheginit**
Project name: Hydrodata

Project website/repository: https://github.com/cheginit/hydrodata

License: MIT

Checklist for new projects:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [ ] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [x] Tests and Travis CI running
- [x] Development status of the project is communicated

- [ ] Easily Accessible
- [ ] Comprehensive and Appealing

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](https://capitalizemytitle.com/#APStyle) (AP style) for project name.

### CODE REVIEW

**Review by mmaelicke — APPROVED** [review]
The project definitely looks awesome and really helpful! Thanks for submitting it. 
I personally like especially your test-suite, nice piece of code. Thanks!

**Comment by cheginit** [comment]
@mmaelicke Thanks! I am glad you find it useful.

**Review by schymans — APPROVED** [review]
Truly AWESOME! Thanks for contributing!

**Comment by schymans** [comment]
Sorry, forgot to confirm merge before closing, so had to re-open.

**Pull request merged**
