### PR TITLE
Adding link to dwdweather2

### PR DESCRIPTION
**Pull request by mmaelicke**
Project name: dwdweather2

Project website/repository: https://github.com/panodata/dwdweather2

License: MIT License

Checklist for new projects:

- [ ] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [x] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [ ] Documentation looks great
- [ ] Examples or Tutorials to follow
- [ ] Tests and Travis CI running
- [x] Development status of the project is communicated

- [ ] Easily Accessible
- [ ] Comprehensive and Appealing

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [ ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

This package is really helpful for downloading open data from the german weather service. However, I see various caveats to placing an awesome label as of now. The maintainers are, however, working on some of them:
- Most important to me: Their Python3 compatibility isssue is still open (still Py2.7)
- docs are too weak to me
- so do the unit tests

Further, I am not sure about the category. It's really closely related to Datasets but is, however, **not** a dataset. Would fit, it the category would be called 'Datasets & Data acquisition'

### CODE REVIEW

**Comment by raoulcollenteur** [comment]
I like the idea of renaming to 'Datasets & Data acquisition'. I think we have to wait for automated tests, documentation and python 3 before approving this PR.

**Comment by raoulcollenteur** [comment]
Wrong button, did not mean to close it..

**Review by schymans — APPROVED** [review]
This one is very close to awesome, but we do have not (yet) awesome links in the list, marked by the absence of the "awesome" icon, just like this one. Therefore I would be happy to include it and add the awesome icon once the maintainers implemented tests.

**Comment by mmaelicke** [comment]
> This one is very close to awesome, but we do have not (yet) awesome links in the list, marked by the absence of the "awesome" icon, just like this one. Therefore I would be happy to include it and add the awesome icon once the maintainers implemented tests.

I agree. I will drop an issue at dwdweather2 informing them about this list and suggest improvements, once the PR is approved and the link is actually there. @schymans, what is your opinion on renaming 'datasets' to 'datasets & data aquisition' and push the link there?

**Comment by schymans** [comment]
I am not sure about mixing data sets and data download scripts in the same category, as it would be nice to have an overview of independent datasets. How about adding another category, "Data mining"?

**Comment by mmaelicke** [comment]
> I am not sure about mixing data sets and data download scripts in the same category, as it would be nice to have an overview of independent datasets. How about adding another category, "Data mining"?

Yeah, that's better. Just didn't feel right to put everything that is not a model under miscellaneous. I'll update.

**Comment by mmaelicke** [comment]
As a quick update: The authors just closed the issue to move to Python 3, so dwdweather2 is now supporting Python > 3.3. Thus I think we can merge the link into the list.

**Review by rcnijzink — APPROVED** [review]
Ok, looks good! Just didn't see the automated testing yet, but let's add it now, it's without the awesome-label then.

**Pull request merged**
