### PR TITLE
Add link to PyMT

### PR DESCRIPTION
**Pull request by mdpiper**
Project name: The Python Modeling Toolkit (PyMT)

Project website/repository: https://github.com/csdms/pymt

License: MIT

Checklist for new projects:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [ ] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [x] Tests and Travis CI running

- [ ] Easily Accessible
- [ ] Comprehensive and Appealing

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Review by schymans — COMMENTED** [review]
I think that this and RINGMesh should go into a new category, ### Frameworks, what do you think? Should we also stick with alphabetical order?

**Comment by mdpiper** [comment]
@schymans PyMT is definitely modeling software. As in https://github.com/Open-Environmental-Science/awesome-open-hydrology/pull/4#issuecomment-627380803, I'd feel bad about modifying the organizational structure of the list.

Note also -- in the PR template, there's a checkbox for "Added the link to the bottom of the relevant category." I agree that alphabetic order is preferable, though.

With your consent, I can move PyMT to the software category and list it in alphabetical order.

**Comment by schymans** [comment]
Yes, agreed, thanks!

**Comment by mdpiper** [comment]
@schymans Moved!

**Review by schymans — APPROVED** [review]
Thank you!

**Review by rcnijzink — APPROVED** [review]
Cool, thanks!

**Pull request merged**
