### PR TITLE
fix link in PR template

### LINKED ISSUE #10: Link in Pull Request template broken
Hey,
The link on the last bullet point in the [Pull Request Template](https://github.com/Open-Environmental-Science/awesome-open-hydrology/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is broken.

I am note sure where it should point to as `http://titlecapitalization.com/`, as well as `https://titlecapitalization.com/` are not working.

What I found is: 

* https://capitalizemytitle.com/
* https://titlecaseconverter.com/
* https://headlinecapitalization.com/

In any case I am not sure what the link was intending. Refering a *converter* or *information* on title capitalization?

### PR DESCRIPTION
**Pull request by mmaelicke**
closes #10

### CODE REVIEW

**Review by mdpiper — APPROVED** [review]
@mmaelicke Thank you for fixing this!

**Review by nielsdrost — APPROVED** [review]
Thanks @mmaelicke for the fix!

**Comment by mmaelicke** [comment]
The CI checks are failing. I don't think the error is related to this pull request:

```
1. [L005]  https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg SSL_connect returned=1 errno=0 state=error: certificate verify failed 
```
It's the awesome badge that is causing the problem, but when I follow the link with the browser the certificate is fine and valid (at least according to chromium and chrome).

But I don't know enough about the `awsome_bot` to actually understand why it is complaining. Anyone suggestions? @schymans ? @mdpiper ?

**Comment by nielsdrost** [comment]
> The CI checks are failing. I don't think the error is related to this pull request:
> 
> ```
> 1. [L005]  https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg SSL_connect returned=1 errno=0 state=error: certificate verify failed 
> ```
> 
> It's the awesome badge that is causing the problem, but when I follow the link with the browser the certificate is fine and valid (at least according to chromium and chrome).
> 
> But I don't know enough about the `awsome_bot` to actually understand why it is complaining. Anyone suggestions? @schymans ? @mdpiper ?

The travis for https://travis-ci.org/github/softwareunderground/awesome-open-geoscience is having the same problem. It seems whatever root certificates are included with travis-ci do not include the one for rawgit.com

**Comment by nielsdrost** [comment]
> > The CI checks are failing. I don't think the error is related to this pull request:
> > ```
> > 1. [L005]  https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg SSL_connect returned=1 errno=0 state=error: certificate verify failed 
> > ```
> > 
> > 
> > It's the awesome badge that is causing the problem, but when I follow the link with the browser the certificate is fine and valid (at least according to chromium and chrome).
> > But I don't know enough about the `awsome_bot` to actually understand why it is complaining. Anyone suggestions? @schymans ? @mdpiper ?
> 
> The travis for https://travis-ci.org/github/softwareunderground/awesome-open-geoscience is having the same problem. It seems whatever root certificates are included with travis-ci do not include the one for rawgit.com

See #12 for a fix: using a newer ubuntu dist in travis seems to do the trick.

**Comment by mmaelicke** [comment]
Thank you all for looking into this and fixing

**Pull request merged**
