### PR TITLE
Add link to Landlab

### PR DESCRIPTION
**Pull request by mdpiper**
Project name: Landlab

Project website/repository: https://github.com/landlab/landlab

License: MIT

Checklist for new projects:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [ ] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [x] Tests and Travis CI running

- [ ] Easily Accessible
- [ ] Comprehensive and Appealing

- [x] Add icon from the `media/icon/` folder if applicable (like `Python` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

### CODE REVIEW

**Comment by mdpiper** [comment]
I just saw that Landlab is listed under "Simulation and Modelling" in https://github.com/softwareunderground/awesome-open-geoscience; perhaps it should be moved to this category instead?

**Comment by schymans** [comment]
Under platforms, I would list online deployments of programs or databases, so I think this repo would better fit under Simulation and Modelling. Or we could add another category, say, "Frameworks"?  
Now that you mention it, Ringmesh should also not be under platforms. Any thoughts?

**Comment by mdpiper** [comment]
@schymans I'd hate to break up the framework (ha!) that you've set up for this list. Landlab is definitely a modeling tool, so I'd be happy to move it to the Simulation and Modeling category.

**Comment by schymans** [comment]
@mdpiper I took the categories directly from  https://github.com/softwareunderground/awesome-open-geoscience and I think that we can modify them for our needs, but you are right, let us stick with their framework for the time being until we have gathered enough experience. Could you modify your PR? Thanks for the discussion!

**Review by mmaelicke — APPROVED** [review]
To me, this looks fine and I will approve.

**Review by schymans — APPROVED** [review]
Great, thank you!

**Pull request merged**
